### ISSUE TITLE
Support missing endpoints

### ISSUE THREAD

**Issue by ctolkien** [useshortcut/clubhouse-lib#23]
- [ ] Story Search
- [ ] Story Bulk Update
- [ ] Story Bulk Create
- [ ] Others?

**Comment by eliperkins** [comment]
Hey @ctolkien! Good catch on those missing endpoints. PRs to add them would be gladly accepted.

In the bigger picture of things, we're hoping to codegen things in the future so that we don't miss endpoints like this.

**Comment by ctolkien** [comment]
>In the bigger picture of things, we're hoping to codegen things in the future so that we don't miss endpoints like this.

To that end, does the clubhouse api expose a swagger/openAPI spec?

**Comment by eliperkins** [comment]
@ctolkien We do not currently expose a OpenAPI definition, as it's derived directly from our source.

If this is something you'd like to see, feel free to open a separate issue, and we can discuss it there!

**Comment by andjosh** [comment]
I believe the new Iterations support should be added here, too, no?

**Comment by eliperkins** [comment]
I'd say so, @andjosh. PRs will definitely be accepted for this!

**Comment by stefanv** [comment]
Looks like the creation of ExternalTickets is also missing.  It would be nice to be able to simply provide a set of GitHub URLs when creating a new story, instead of having to manually create an object for each.

**Comment by kazkovsky** [comment]
I think that Get Epic Workflow is also missing? Search Epics also? Guys this is commercial product not some open source alpha project. Get yourself together and add missing endpoints :(

**Comment by kelkes** [comment]
Would be nice if we could add `external_tickets` when updating stories.

**Comment by charpeni** [comment]
Hey @kazkovsky, thanks for reaching out!

I understand your frustration here. We initially open-sourced what we had internally for some of our JavaScript projects to be transparent and provide something useful to our community. However, since then we’ve moved from the REST API to GraphQL which is the main reason why this library hasn’t been updated to include the endpoints you listed. In the future, we hope to provide a Swagger / Open API definition to make it even easier to keep up to date.

In spite of the fact that we don’t actively rely on this ourselves, we have spent quite a bit of time maintaining it:
- We moved to TypeScript, improved our types, and added a significant number of missing endpoints.
- We improved the developer experience by sharing a CodeSandbox where you can play with this library and the API from your browser.
- We made, polished, and open-sourced documentation for our latest API (v3), available at https://clubhouse.io/api/rest/v3/.

Additionally, we’ve been spending time improving the product directly, so hopefully, you won't have to rely on the API to complete useful tasks.

We appreciate everyone who contributes to this library, and of course, PRs welcome.

**Comment by kelkes** [comment]
I would totally use GraphQL over a REST API any day :) Any plans on making it public?

**Comment by charpeni** [comment]
I can't commit to a public GraphQL API at the moment as we're still in the early stage, and this is not complete enough to be shared or used externally. We'll see how it goes.

I was looking at `external_tickets` and I came to the same conclusion as you did. It seems like `external_tickets` are only available during story creation. I'll check with the backend team on this and I'll let you know. Thanks for looking into this!

**Comment by jeremyheiler** [comment]
@kelkes: We have a plan for adding dedicated endpoints for managing external tickets. Stay tuned!

**Comment by ctolkien** [comment]
I feel like.. adding OpenAPI would solve all these issues. Not just for a lack of JS client but for all clients.

But if you're moving to GraphQL ¯\_(ツ)_/¯

**Comment by kelkes** [comment]
Any progress on the `external_tickets` topic?

**Comment by kelkes** [comment]
Our usage of clubhouse would greatly benefit from an API update where we can finally add external_tickets... any updates? 

![2020-03-10_16-15](https://user-images.githubusercontent.com/204445/76327571-77343180-62ea-11ea-96b8-104c0a934b16.png)

**Comment by ctolkien** [comment]
@kelkes  - this is your time tracking solution I take it?

**Comment by kelkes** [comment]
Right, we use the (amazing) clubhouse webhook api to create tasks in harvest for easier time tracking. Since i can't add external_tickets via updateStory, adding a label was our workaround.

**Comment by kelkes** [comment]
Any progress on this topic? I could really use that update :) The workaround renders labels useless for us...

**Comment by ctolkien** [comment]
I've no plans to add these @kelkes  - the ClubHouse team may. As I raised before, if we had an OpenAPI doc the clients could simply be codegen'd and we wouldn't have these isssues!

**Comment by kelkes** [comment]
Oh did i miss out something? I thought you were related to the clubhouse team. sorry for that

**Comment by kelkes** [comment]
@jeremyheiler any update on that?

**Comment by Evilweed** [comment]
Any update?

**Comment by charpeni** [comment]
Closing this in favor of #126.

We are currently rewriting this library to be a generated TypeScript client from a Swagger/OpenAPI schema.
