### ISSUE TITLE
Response body swallowed on API Error

### ISSUE THREAD

**Issue by alexlafroscia** [useshortcut/clubhouse-lib#65]
If you run into an error when accessing the API, this code gets executed:

https://github.com/clubhouse/clubhouse-lib/blob/c6f62deb624c5de83d1a05d42f6ca9579ef2bb5e/src/FetchRequestParser.ts#L10-L17

It _seems_ like `ClientError` would be called with `response` and the parsed `body`, but unfortunately the `.catch` grabs that error that's thrown, swallows it, and throws another error with a regular POJO instead.

Because the `response.body` has already been parsed, you can't use the `response` object on the error to call `.json()` again to get the value. `.clone()` _also_ doesn't work because `body` was already parsed.

It would be really nice to re-throw the original error if the thing that's caught is already a `ClientError` instance! If you're interested in a fix like that, I would be happy to put together a PR.

The result of this is that it's hard to log the body of the error, in a case where you're using this library in a script and just want to see what went wrong!

**Comment by kenficara** [comment]
Was this pull not merged, or is there another solution in the works? I ran into this today when I got "422: Unprocessable Entity" back from the API, when the actual response included the more useful information that I was trying to add an epic to a milestone it was already part of. I ended up making my own request rather than using the library.

**Comment by alexlafroscia** [comment]
I don't know that there was ever a pull request associated with this; I just opened the bug report that was never acknowledged by anyone at Clubhouse 🤷‍♂️

**Comment by Evilweed** [comment]
@danhawkins or anyone really - this issue makes development of tools using this library super hard. 

Please help 🙏

**Comment by charpeni** [comment]
Sorry for the delay here!

Unfortunately, we're not using this `FetchRequestParser`. Feel free to send a PR our way, I'll be happy to review it, and faster than responding to this issue. 🙃

**Comment by Evilweed** [comment]
Dear @charpeni, i just modified on my computer FetchRequestParser, the one you told us you don't use, and turns out you use it. Logs show it is being used to process requests.

I also managed to modify this in a way that it does not remove error data from body and just reformats it.
```
class FetchRequestParser implements ResponseParser<Response> {
  public readonly parseResponse = (
    response: Response,
  ): Promise<Record<string, any>> =>
    response
      .json()
      .then((json: Record<string, any>) => {
        if (response.ok) {
          return json;
        }

        return Promise.reject(new ClientError(response, json));
      })
      .catch((err) => {
         // If there is an error, the "err.body" looks for example like this "{ message: 'Resource not found.' }"
         const returnValue = { error: err.body } || {}. // <---- ✅ Changed this line
         Promise.reject(new ClientError(response, returnValue)) // <---- ✅ Changed this line
      );
}
```
# After adding this change:
![CleanShot 2021-08-29 at 18 49 40@2x](https://user-images.githubusercontent.com/5477821/131258583-f6ce4cb5-70eb-4b33-bafb-dd92e8bed86b.png)


So please fix this... It is ridiculously awful to develop in a framework that just swallows errors and User has no idea what he/she did wrong.

**Comment by charpeni** [comment]
Closing this in favor of #126.

We are currently rewriting this library to be a generated TypeScript client from a Swagger/OpenAPI schema.
